
services:
  - type: web
    name: whatsapp-gpt-bot
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --threads 4 --timeout 60
    autoDeploy: true
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: WHATSAPP_TOKEN
        sync: false
      - key: PHONE_ID
        sync: false
      - key: VERIFY_TOKEN
        sync: false
      - key: GRAPH_API_VERSION
        value: v18.0
